### ISSUE TITLE
Some problems about introduction

### ISSUE THREAD

**Issue by Rahmatreaza** [ami-karimi/onyx_werewolf#1]
سلام
ببخشید داخل اینتروداکشن شما چون فارسی انگلیسی نوشتید خیلی سخته خوندن پیش نیاز ها 
لطفا یا فقط انگلیسی بنویسید
یا فقط فارسی 
یا اگر میتونید درستش کنید . 
ممنونم 😃
Hi
Sorry in introductioncause you wrote persian and english together the Sentences had broke .
If you can please fix it . Thank you very much .

**Comment by ami-karimi** [comment]
سلام وقت بخیر هنوز تکمیل نشده داکیومنت بزودی تکمیل میکنم و توضیحات کامل رو قرار میدم برای هر بخش

**Comment by Rahmatreaza** [comment]
ممنونم بابت پاسخگویی
